% regressionPresentationRnw
% R code style:
%\DefineVerbatimEnvironment{Sinput}{Verbatim}{xleftmargin=2em}
%\DefineVerbatimEnvironment{Soutput}{Verbatim}{xleftmargin=2em}
%\DefineVerbatimEnvironment{Scode}{Verbatim}{xleftmargin=2em}
%\fvset{listparameters={\setlength{\topsep}{0pt}}}
%\renewenvironment{Schunk}{\vspace{\topsep}}{\vspace{\topsep}}
\documentclass {beamer}
\usetheme{Rochester}
\usepackage[utf8]{inputenc}
\begin{document}
%Shortens output lines
<<echo=false>>=
options(width=60)
options(continue=" ")
@
\begin{frame}[fragile]{Regression: Least-squares, Maximum Likelihood und Bayes}
\begin{small}
\end{small}
\end{frame}
\begin{frame}[fragile]{Dataset}
\begin{small}
<<loadProfitData>>=
profitData <- read.table("ex1data2.txt", 
                            header=TRUE, sep=",")
head(profitData)
nrow(profitData)
@
\end{small}
\end{frame}
\begin{frame}[fragile]{Dataset}
\begin{small}
<<displayProfitData, fig=true, echo=false>>=
#lines(density(profitData$price))
#head(profitData$price)
#hist(profitData$price, breaks=10,prob=T)
pairs(profitData[,c(1,2,3)])
#plot(1:10)
@
\end{small}
\end{frame}
\begin{frame}[fragile]{Dataset}
\begin{small}
<<displayProfitData2, fig=true, echo=false, include=false,width=6,height=4>>=
#lines(density(profitData$price))
#head(profitData$price)
#hist(profitData$price, breaks=10,prob=T)
plot(price~house_size,data=profitData, xlab="Size of the house",
        yaxt="n",ylab="Price");
ymin=min(profitData[,3])
ymax=max(profitData[,3])
axis(2, at=c(ymin, (ymin+ymax)/2, ymax))
        
model<-lm(price~house_size,data=profitData)
abline(model)
#plot(1:10)
@
\begin{figure}[tbp]
\centering
\includegraphics{regressionPresentation-displayProfitData2}
\end{figure}
\end{small}
\end{frame}

\begin{frame}
A displayed formula:
\[
  \int_{-\infty}^\infty e^{-x^2} \, dx = \sqrt{\pi}
\]

An itemized list:

\begin{itemize}
  \item itemized item 1
  \item itemized item 2
  \item itemized item 3
\end{itemize}

\begin{theorem}
  In a right triangle, the square of hypotenuse equals
  the sum of squares of two other sides.
\end{theorem}

\end{frame}
\begin{frame}[fragile]{Logistic Regression}
\begin{small}
<<loadTitanicData>>=
titanicData <- read.csv(file="titanicTrain.csv", 
                head=TRUE,sep=",")
@
\end{small}
survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,,S

\end{frame}
\begin{frame}{Applications}
Phylogenetic Trees: wikipedia
\end{frame}
\end{document}
